### PR TITLE
chore(action): reusable tag

### PR DESCRIPTION
**Pull request by vhemery**
Closes [CI-910](https://bonitasoft.atlassian.net/browse/CI-910)

[CI-910]: https://bonitasoft.atlassian.net/browse/CI-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by vhemery** [comment]
Needs rebase after https://github.com/bonitasoft/bonita-project/pull/66 is merged

**Review by rbioteau — APPROVED** [review]

**Comment by rbioteau** [comment]
@vhemery could you sign your commits ? :smile:

**Comment by vhemery** [comment]
> @vhemery could you sign your commits ? 😄

I don't get it. My non-signed commits are the ones from Github UI... Can't figure out why Github no longer signs commits... 😨

**Comment by vhemery** [comment]
I've had this issue in another PR on a deleted branch which I restored. So that could explain it.

Here, the non-signed commits are marked as "@[vhemery](https://github.com/bonitasoft/bonita-project/commits?author=vhemery)
@[rbioteau](https://github.com/bonitasoft/bonita-project/commits?author=rbioteau)
vhemery authored and rbioteau committed"
Don't know what happened here...

**Pull request merged**
